### ISSUE TITLE
Hardcoding User ID in File Display Servlet  

### ISSUE THREAD

**Issue by CharlesJ10** [googleinterns/step2-2020#20]
To have a minimum viable product, we hardcoded the userId as the login / upload data is being completed. We need to remove this hardcoded data once the upload/login stuff is done.
https://github.com/googleinterns/step2-2020/pull/17/commits/b95f7bc94cbeffdf4bd78f4374948516f0828e48#r447248779

**Comment by Chronos34** [comment]
Fixed in #33
